name: Bank-Api CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: bankDb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install migrate
        run: |
          $ curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-386.deb | tar xvz
          which migrate

      - name: Run migrations
        run: make migrate-up

      - name: Test
        run: make test
